# Generated by Django 4.2 on 2024-10-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='grayscale_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/grayscale/'),
        ),
        migrations.AddField(
            model_name='image',
            name='resized_100_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/resized_100/'),
        ),
        migrations.AddField(
            model_name='image',
            name='resized_500_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/resized_500/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_path',
            field=models.ImageField(upload_to='images/original/'),
        ),
    ]
