# Generated by Django 4.2 on 2024-10-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_format_image_grayscale_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='grayscale_path',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_path',
            field=models.ImageField(upload_to='images/media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resized_100_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/media/resized_100/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resized_500_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/media/resized_500/'),
        ),
    ]
